### ISSUE TITLE
Workflow for publishing a new release to PyPi

### ISSUE THREAD

**Issue by AdamFiser** [andreasnuesslein/py-teleco-daisy#8]
To ensure continuous development and process automation, define a github workflow for publishing the package to PyPi

**Comment by AdamFiser** [comment]
Hi @andreasnuesslein can you please set in PyPi new publisher? Im preparing new github workflow 'publish.yml'

[how to](https://medium.com/@blackary/publishing-a-python-package-from-github-to-pypi-in-2024-a6fb8635d45d)

**Comment by andreasnuesslein** [comment]
hey @AdamFiser ; done!  can you take care of the `publish.yml`?
